### ISSUE TITLE
Callout Color

### ISSUE THREAD

**Issue by lorenzlm** [lguenth/obsidian-templates#1]
Hi. I have installed your carefully designed zotero/obsidian-template (thank you!). What doesn't seem to work with me is the color-coding of the callouts in the Note section, according to the colors of the Zotero annotations. All callouts stay grey... I have tried to find more information about the syntax that you and others are using: [!callouttype|color] - but without success. It's unclear to me whether an additional css-Snippet might be necessary or what else could be my problem. Advice would be welcome. :)

**Comment by lguenth** [comment]
Hey, I'm glad you like it!
And... whoops! I did indeed forget to mention that I'm using a CSS snippet to go along with the template which targets callouts with the colour attribute. I will make sure to add that here and on the forum! Thanks! :orange_heart: 

It's originally from mgmeyers, I've just changed the colours to those used by Zotero itself (I think). If you only want this to only be applied in specific notes, you can uncomment the `.literature-note` line for each and put `cssclass: literature-note` in the YAML frontmatter of the notes you want to apply it to (or, better yet, in the template).

The snippet:
```css
/* Yellow */
/* .literature-note  */
.callout[data-callout-metadata="yellow"] {
  --callout-color: 255, 212, 0 !important;
}

/* Red */
/* .literature-note  */
.callout[data-callout-metadata="red"] {
  --callout-color: 255, 102, 102 !important;
}

/* Orange */
/* .literature-note  */
.callout[data-callout-metadata="orange"] {
  --callout-color: 241, 152, 55 !important;
}

/* Green */
/* .literature-note  */
.callout[data-callout-metadata="green"] {
  --callout-color: 95, 178, 54 !important;
}

/* Blue */
/* .literature-note  */
.callout[data-callout-metadata="blue"] {
  --callout-color: 46, 168, 229 !important;
}

/* Magenta */
/* .literature-note  */
.callout[data-callout-metadata="magenta"] {
  --callout-color: 229, 110, 238 !important;
}

/* Pink */
/* .literature-note  */
.callout[data-callout-metadata="pink"] {
  --callout-color: 229, 110, 238 !important;
}

/* Purple */
/* .literature-note  */
.callout[data-callout-metadata="purple"] {
  --callout-color: 162, 138, 229 !important;
}

/* Grey */
/* .literature-note  */
.callout[data-callout-metadata="grey"] {
  --callout-color: 170, 170, 170 !important;
}
```
